// Code generated by pigeon; DO NOT EDIT.

package peg

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"github.com/raralabs/canal/utils/cast"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Main",
			pos:  position{line: 5, col: 1, offset: 21},
			expr: &actionExpr{
				pos: position{line: 5, col: 9, offset: 29},
				run: (*parser).callonMain1,
				expr: &seqExpr{
					pos: position{line: 5, col: 9, offset: 29},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 5, col: 9, offset: 29},
							label: "agg",
							expr: &ruleRefExpr{
								pos:  position{line: 5, col: 13, offset: 33},
								name: "Job",
							},
						},
						&labeledExpr{
							pos:   position{line: 5, col: 17, offset: 37},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 5, col: 22, offset: 42},
								expr: &seqExpr{
									pos: position{line: 5, col: 23, offset: 43},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 5, col: 23, offset: 43},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 5, col: 25, offset: 45},
											val:        "|",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 5, col: 29, offset: 49},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 5, col: 31, offset: 51},
											name: "Job",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Expr",
			pos:  position{line: 22, col: 1, offset: 343},
			expr: &actionExpr{
				pos: position{line: 22, col: 9, offset: 351},
				run: (*parser).callonExpr1,
				expr: &seqExpr{
					pos: position{line: 22, col: 9, offset: 351},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 22, col: 9, offset: 351},
							name: "Variable",
						},
						&zeroOrMoreExpr{
							pos: position{line: 22, col: 18, offset: 360},
							expr: &seqExpr{
								pos: position{line: 22, col: 20, offset: 362},
								exprs: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 22, col: 20, offset: 362},
										name: "_",
									},
									&choiceExpr{
										pos: position{line: 22, col: 23, offset: 365},
										alternatives: []interface{}{
											&litMatcher{
												pos:        position{line: 22, col: 23, offset: 365},
												val:        "%",
												ignoreCase: false,
											},
											&litMatcher{
												pos:        position{line: 22, col: 29, offset: 371},
												val:        "-",
												ignoreCase: false,
											},
											&litMatcher{
												pos:        position{line: 22, col: 35, offset: 377},
												val:        "+",
												ignoreCase: false,
											},
											&litMatcher{
												pos:        position{line: 22, col: 41, offset: 383},
												val:        "*",
												ignoreCase: false,
											},
											&litMatcher{
												pos:        position{line: 22, col: 47, offset: 389},
												val:        "/",
												ignoreCase: false,
											},
										},
									},
									&ruleRefExpr{
										pos:  position{line: 22, col: 52, offset: 394},
										name: "_",
									},
									&choiceExpr{
										pos: position{line: 22, col: 55, offset: 397},
										alternatives: []interface{}{
											&ruleRefExpr{
												pos:  position{line: 22, col: 55, offset: 397},
												name: "Variable_Value",
											},
											&ruleRefExpr{
												pos:  position{line: 22, col: 72, offset: 414},
												name: "Number",
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Value",
			pos:  position{line: 26, col: 1, offset: 468},
			expr: &actionExpr{
				pos: position{line: 26, col: 10, offset: 477},
				run: (*parser).callonValue1,
				expr: &labeledExpr{
					pos:   position{line: 26, col: 10, offset: 477},
					label: "val",
					expr: &choiceExpr{
						pos: position{line: 26, col: 15, offset: 482},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 26, col: 15, offset: 482},
								name: "Number",
							},
							&ruleRefExpr{
								pos:  position{line: 26, col: 24, offset: 491},
								name: "String_Type1",
							},
							&ruleRefExpr{
								pos:  position{line: 26, col: 39, offset: 506},
								name: "Variable_Literal",
							},
							&ruleRefExpr{
								pos:  position{line: 26, col: 58, offset: 525},
								name: "Variable_Value",
							},
						},
					},
				},
			},
		},
		{
			name: "Variable",
			pos:  position{line: 30, col: 1, offset: 574},
			expr: &actionExpr{
				pos: position{line: 30, col: 13, offset: 586},
				run: (*parser).callonVariable1,
				expr: &seqExpr{
					pos: position{line: 30, col: 13, offset: 586},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 30, col: 13, offset: 586},
							name: "Letter",
						},
						&zeroOrMoreExpr{
							pos: position{line: 30, col: 20, offset: 593},
							expr: &choiceExpr{
								pos: position{line: 30, col: 21, offset: 594},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 30, col: 21, offset: 594},
										name: "Integer",
									},
									&ruleRefExpr{
										pos:  position{line: 30, col: 31, offset: 604},
										name: "Letter",
									},
									&litMatcher{
										pos:        position{line: 30, col: 39, offset: 612},
										val:        "_",
										ignoreCase: false,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Variable_Value",
			pos:  position{line: 34, col: 1, offset: 662},
			expr: &actionExpr{
				pos: position{line: 34, col: 19, offset: 680},
				run: (*parser).callonVariable_Value1,
				expr: &seqExpr{
					pos: position{line: 34, col: 19, offset: 680},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 34, col: 19, offset: 680},
							val:        "$",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 34, col: 23, offset: 684},
							label: "vrbl",
							expr: &ruleRefExpr{
								pos:  position{line: 34, col: 28, offset: 689},
								name: "Variable",
							},
						},
					},
				},
			},
		},
		{
			name: "Variable_Literal",
			pos:  position{line: 38, col: 1, offset: 728},
			expr: &actionExpr{
				pos: position{line: 38, col: 21, offset: 748},
				run: (*parser).callonVariable_Literal1,
				expr: &labeledExpr{
					pos:   position{line: 38, col: 21, offset: 748},
					label: "vrbl",
					expr: &ruleRefExpr{
						pos:  position{line: 38, col: 26, offset: 753},
						name: "Variable",
					},
				},
			},
		},
		{
			name: "String_Type1",
			pos:  position{line: 43, col: 1, offset: 850},
			expr: &actionExpr{
				pos: position{line: 43, col: 17, offset: 866},
				run: (*parser).callonString_Type11,
				expr: &seqExpr{
					pos: position{line: 43, col: 17, offset: 866},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 43, col: 17, offset: 866},
							val:        "\"",
							ignoreCase: false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 43, col: 21, offset: 870},
							expr: &choiceExpr{
								pos: position{line: 43, col: 23, offset: 872},
								alternatives: []interface{}{
									&seqExpr{
										pos: position{line: 43, col: 23, offset: 872},
										exprs: []interface{}{
											&notExpr{
												pos: position{line: 43, col: 23, offset: 872},
												expr: &ruleRefExpr{
													pos:  position{line: 43, col: 24, offset: 873},
													name: "EscapedChar",
												},
											},
											&anyMatcher{
												line: 43, col: 36, offset: 885,
											},
										},
									},
									&seqExpr{
										pos: position{line: 43, col: 40, offset: 889},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 43, col: 40, offset: 889},
												val:        "\\",
												ignoreCase: false,
											},
											&ruleRefExpr{
												pos:  position{line: 43, col: 45, offset: 894},
												name: "EscapeSequence",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 43, col: 63, offset: 912},
							val:        "\"",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "EscapedChar",
			pos:  position{line: 50, col: 1, offset: 1093},
			expr: &charClassMatcher{
				pos:        position{line: 50, col: 16, offset: 1108},
				val:        "[\\x00-\\x1f\"\\\\]",
				chars:      []rune{'"', '\\'},
				ranges:     []rune{'\x00', '\x1f'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EscapeSequence",
			pos:  position{line: 52, col: 1, offset: 1126},
			expr: &ruleRefExpr{
				pos:  position{line: 52, col: 19, offset: 1144},
				name: "SingleCharEscape",
			},
		},
		{
			name: "SingleCharEscape",
			pos:  position{line: 54, col: 1, offset: 1164},
			expr: &charClassMatcher{
				pos:        position{line: 54, col: 21, offset: 1184},
				val:        "[\"\\\\/bfnrt]",
				chars:      []rune{'"', '\\', '/', 'b', 'f', 'n', 'r', 't'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Word",
			pos:  position{line: 56, col: 1, offset: 1199},
			expr: &actionExpr{
				pos: position{line: 56, col: 9, offset: 1207},
				run: (*parser).callonWord1,
				expr: &oneOrMoreExpr{
					pos: position{line: 56, col: 9, offset: 1207},
					expr: &choiceExpr{
						pos: position{line: 56, col: 10, offset: 1208},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 56, col: 10, offset: 1208},
								name: "Letter",
							},
							&litMatcher{
								pos:        position{line: 56, col: 19, offset: 1217},
								val:        "_",
								ignoreCase: false,
							},
						},
					},
				},
			},
		},
		{
			name: "Letter",
			pos:  position{line: 60, col: 1, offset: 1267},
			expr: &choiceExpr{
				pos: position{line: 60, col: 11, offset: 1277},
				alternatives: []interface{}{
					&charClassMatcher{
						pos:        position{line: 60, col: 11, offset: 1277},
						val:        "[a-z]",
						ranges:     []rune{'a', 'z'},
						ignoreCase: false,
						inverted:   false,
					},
					&charClassMatcher{
						pos:        position{line: 60, col: 19, offset: 1285},
						val:        "[A-Z]",
						ranges:     []rune{'A', 'Z'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 62, col: 1, offset: 1294},
			expr: &actionExpr{
				pos: position{line: 62, col: 11, offset: 1304},
				run: (*parser).callonNumber1,
				expr: &seqExpr{
					pos: position{line: 62, col: 11, offset: 1304},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 62, col: 11, offset: 1304},
							expr: &litMatcher{
								pos:        position{line: 62, col: 11, offset: 1304},
								val:        "-",
								ignoreCase: false,
							},
						},
						&ruleRefExpr{
							pos:  position{line: 62, col: 16, offset: 1309},
							name: "Integer",
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 66, col: 1, offset: 1382},
			expr: &choiceExpr{
				pos: position{line: 66, col: 12, offset: 1393},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 66, col: 12, offset: 1393},
						val:        "0",
						ignoreCase: false,
					},
					&seqExpr{
						pos: position{line: 66, col: 18, offset: 1399},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 66, col: 18, offset: 1399},
								name: "NonZeroDecimalDigit",
							},
							&zeroOrMoreExpr{
								pos: position{line: 66, col: 38, offset: 1419},
								expr: &ruleRefExpr{
									pos:  position{line: 66, col: 38, offset: 1419},
									name: "DecimalDigit",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DecimalDigit",
			pos:  position{line: 68, col: 1, offset: 1436},
			expr: &charClassMatcher{
				pos:        position{line: 68, col: 17, offset: 1452},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "NonZeroDecimalDigit",
			pos:  position{line: 70, col: 1, offset: 1461},
			expr: &charClassMatcher{
				pos:        position{line: 70, col: 24, offset: 1484},
				val:        "[1-9]",
				ranges:     []rune{'1', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 72, col: 1, offset: 1493},
			expr: &zeroOrMoreExpr{
				pos: position{line: 72, col: 19, offset: 1511},
				expr: &charClassMatcher{
					pos:        position{line: 72, col: 19, offset: 1511},
					val:        "[ \\t\\r\\n]",
					chars:      []rune{' ', '\t', '\r', '\n'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "OneWhiteSpace",
			pos:  position{line: 74, col: 1, offset: 1525},
			expr: &charClassMatcher{
				pos:        position{line: 74, col: 18, offset: 1542},
				val:        "[ \\t\\r\\n]",
				chars:      []rune{' ', '\t', '\r', '\n'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EOF",
			pos:  position{line: 76, col: 1, offset: 1555},
			expr: &notExpr{
				pos: position{line: 76, col: 8, offset: 1562},
				expr: &anyMatcher{
					line: 76, col: 9, offset: 1563,
				},
			},
		},
		{
			name: "Job",
			pos:  position{line: 80, col: 1, offset: 1579},
			expr: &choiceExpr{
				pos: position{line: 80, col: 8, offset: 1586},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 80, col: 8, offset: 1586},
						name: "FileJobG",
					},
					&ruleRefExpr{
						pos:  position{line: 80, col: 19, offset: 1597},
						name: "DoJobG",
					},
					&ruleRefExpr{
						pos:  position{line: 80, col: 28, offset: 1606},
						name: "AggJobG",
					},
					&ruleRefExpr{
						pos:  position{line: 80, col: 38, offset: 1616},
						name: "SinkJobG",
					},
				},
			},
		},
		{
			name: "FileJobG",
			pos:  position{line: 82, col: 1, offset: 1628},
			expr: &actionExpr{
				pos: position{line: 82, col: 13, offset: 1640},
				run: (*parser).callonFileJobG1,
				expr: &seqExpr{
					pos: position{line: 82, col: 13, offset: 1640},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 82, col: 13, offset: 1640},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 82, col: 15, offset: 1642},
							val:        "file(",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 82, col: 23, offset: 1650},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 82, col: 25, offset: 1652},
							label: "filename",
							expr: &ruleRefExpr{
								pos:  position{line: 82, col: 34, offset: 1661},
								name: "FileName",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 82, col: 43, offset: 1670},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 82, col: 45, offset: 1672},
							val:        ")",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "FileName",
			pos:  position{line: 89, col: 1, offset: 1854},
			expr: &actionExpr{
				pos: position{line: 89, col: 13, offset: 1866},
				run: (*parser).callonFileName1,
				expr: &seqExpr{
					pos: position{line: 89, col: 13, offset: 1866},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 89, col: 13, offset: 1866},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 89, col: 18, offset: 1871},
								name: "Variable",
							},
						},
						&litMatcher{
							pos:        position{line: 89, col: 27, offset: 1880},
							val:        ".",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 89, col: 31, offset: 1884},
							label: "ext",
							expr: &ruleRefExpr{
								pos:  position{line: 89, col: 35, offset: 1888},
								name: "Variable",
							},
						},
					},
				},
			},
		},
		{
			name: "DoJobG",
			pos:  position{line: 96, col: 1, offset: 2007},
			expr: &actionExpr{
				pos: position{line: 96, col: 11, offset: 2017},
				run: (*parser).callonDoJobG1,
				expr: &labeledExpr{
					pos:   position{line: 96, col: 11, offset: 2017},
					label: "job",
					expr: &choiceExpr{
						pos: position{line: 96, col: 16, offset: 2022},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 96, col: 16, offset: 2022},
								name: "FilterDo",
							},
							&ruleRefExpr{
								pos:  position{line: 96, col: 27, offset: 2033},
								name: "BranchDo",
							},
						},
					},
				},
			},
		},
		{
			name: "AggJobG",
			pos:  position{line: 100, col: 1, offset: 2097},
			expr: &actionExpr{
				pos: position{line: 100, col: 12, offset: 2108},
				run: (*parser).callonAggJobG1,
				expr: &seqExpr{
					pos: position{line: 100, col: 12, offset: 2108},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 100, col: 12, offset: 2108},
							label: "job",
							expr: &ruleRefExpr{
								pos:  position{line: 100, col: 16, offset: 2112},
								name: "AggJobs",
							},
						},
						&labeledExpr{
							pos:   position{line: 100, col: 24, offset: 2120},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 100, col: 29, offset: 2125},
								expr: &seqExpr{
									pos: position{line: 100, col: 30, offset: 2126},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 100, col: 30, offset: 2126},
											val:        ",",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 100, col: 34, offset: 2130},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 100, col: 36, offset: 2132},
											name: "AggJobs",
										},
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 100, col: 46, offset: 2142},
							label: "params",
							expr: &zeroOrOneExpr{
								pos: position{line: 100, col: 53, offset: 2149},
								expr: &ruleRefExpr{
									pos:  position{line: 100, col: 53, offset: 2149},
									name: "AggGroupBy",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "AggJobs",
			pos:  position{line: 114, col: 1, offset: 2491},
			expr: &choiceExpr{
				pos: position{line: 114, col: 12, offset: 2502},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 114, col: 12, offset: 2502},
						name: "CountAgg",
					},
					&ruleRefExpr{
						pos:  position{line: 114, col: 23, offset: 2513},
						name: "MaxAgg",
					},
					&ruleRefExpr{
						pos:  position{line: 114, col: 32, offset: 2522},
						name: "MinAgg",
					},
					&ruleRefExpr{
						pos:  position{line: 114, col: 41, offset: 2531},
						name: "AvgAgg",
					},
					&ruleRefExpr{
						pos:  position{line: 114, col: 50, offset: 2540},
						name: "VarAgg",
					},
				},
			},
		},
		{
			name: "AggGroupBy",
			pos:  position{line: 116, col: 1, offset: 2550},
			expr: &actionExpr{
				pos: position{line: 116, col: 15, offset: 2564},
				run: (*parser).callonAggGroupBy1,
				expr: &seqExpr{
					pos: position{line: 116, col: 15, offset: 2564},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 116, col: 15, offset: 2564},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 116, col: 17, offset: 2566},
							val:        "by ",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 116, col: 23, offset: 2572},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 116, col: 25, offset: 2574},
							label: "param",
							expr: &ruleRefExpr{
								pos:  position{line: 116, col: 31, offset: 2580},
								name: "Variable",
							},
						},
						&labeledExpr{
							pos:   position{line: 116, col: 40, offset: 2589},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 116, col: 45, offset: 2594},
								expr: &seqExpr{
									pos: position{line: 116, col: 46, offset: 2595},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 116, col: 46, offset: 2595},
											val:        ",",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 116, col: 50, offset: 2599},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 116, col: 52, offset: 2601},
											name: "Variable",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SinkJobG",
			pos:  position{line: 130, col: 1, offset: 2957},
			expr: &choiceExpr{
				pos: position{line: 130, col: 13, offset: 2969},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 130, col: 13, offset: 2969},
						name: "StdOutG",
					},
					&ruleRefExpr{
						pos:  position{line: 130, col: 23, offset: 2979},
						name: "BlackHoleG",
					},
				},
			},
		},
		{
			name: "StdOutG",
			pos:  position{line: 132, col: 1, offset: 2993},
			expr: &actionExpr{
				pos: position{line: 132, col: 12, offset: 3004},
				run: (*parser).callonStdOutG1,
				expr: &litMatcher{
					pos:        position{line: 132, col: 12, offset: 3004},
					val:        "stdout()",
					ignoreCase: false,
				},
			},
		},
		{
			name: "BlackHoleG",
			pos:  position{line: 136, col: 1, offset: 3068},
			expr: &actionExpr{
				pos: position{line: 136, col: 15, offset: 3082},
				run: (*parser).callonBlackHoleG1,
				expr: &litMatcher{
					pos:        position{line: 136, col: 15, offset: 3082},
					val:        "blackhole()",
					ignoreCase: false,
				},
			},
		},
		{
			name: "FilterDo",
			pos:  position{line: 143, col: 1, offset: 3175},
			expr: &actionExpr{
				pos: position{line: 143, col: 13, offset: 3187},
				run: (*parser).callonFilterDo1,
				expr: &seqExpr{
					pos: position{line: 143, col: 13, offset: 3187},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 143, col: 13, offset: 3187},
							val:        "filter(",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 143, col: 23, offset: 3197},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 143, col: 25, offset: 3199},
							label: "filt",
							expr: &ruleRefExpr{
								pos:  position{line: 143, col: 30, offset: 3204},
								name: "FilterMulti",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 143, col: 42, offset: 3216},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 143, col: 44, offset: 3218},
							val:        ")",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "FilterMulti",
			pos:  position{line: 152, col: 1, offset: 3504},
			expr: &actionExpr{
				pos: position{line: 152, col: 16, offset: 3519},
				run: (*parser).callonFilterMulti1,
				expr: &seqExpr{
					pos: position{line: 152, col: 16, offset: 3519},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 152, col: 16, offset: 3519},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 152, col: 22, offset: 3525},
								name: "FilterFactor",
							},
						},
						&labeledExpr{
							pos:   position{line: 152, col: 35, offset: 3538},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 152, col: 40, offset: 3543},
								expr: &seqExpr{
									pos: position{line: 152, col: 41, offset: 3544},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 152, col: 41, offset: 3544},
											name: "_",
										},
										&labeledExpr{
											pos:   position{line: 152, col: 43, offset: 3546},
											label: "op",
											expr: &ruleRefExpr{
												pos:  position{line: 152, col: 46, offset: 3549},
												name: "FilterSecOp",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 152, col: 58, offset: 3561},
											name: "_",
										},
										&labeledExpr{
											pos:   position{line: 152, col: 60, offset: 3563},
											label: "f2",
											expr: &ruleRefExpr{
												pos:  position{line: 152, col: 63, offset: 3566},
												name: "FilterFactor",
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "FilterFactor",
			pos:  position{line: 157, col: 1, offset: 3724},
			expr: &choiceExpr{
				pos: position{line: 157, col: 17, offset: 3740},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 157, col: 17, offset: 3740},
						run: (*parser).callonFilterFactor2,
						expr: &seqExpr{
							pos: position{line: 157, col: 17, offset: 3740},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 157, col: 17, offset: 3740},
									val:        "(",
									ignoreCase: false,
								},
								&labeledExpr{
									pos:   position{line: 157, col: 21, offset: 3744},
									label: "sf",
									expr: &ruleRefExpr{
										pos:  position{line: 157, col: 24, offset: 3747},
										name: "FilterMulti",
									},
								},
								&litMatcher{
									pos:        position{line: 157, col: 36, offset: 3759},
									val:        ")",
									ignoreCase: false,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 159, col: 5, offset: 3790},
						run: (*parser).callonFilterFactor8,
						expr: &labeledExpr{
							pos:   position{line: 159, col: 5, offset: 3790},
							label: "pf",
							expr: &ruleRefExpr{
								pos:  position{line: 159, col: 8, offset: 3793},
								name: "FilterPrimary",
							},
						},
					},
				},
			},
		},
		{
			name: "FilterSecOp",
			pos:  position{line: 163, col: 1, offset: 3835},
			expr: &choiceExpr{
				pos: position{line: 163, col: 16, offset: 3850},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 163, col: 16, offset: 3850},
						val:        "and",
						ignoreCase: false,
					},
					&actionExpr{
						pos: position{line: 163, col: 24, offset: 3858},
						run: (*parser).callonFilterSecOp3,
						expr: &litMatcher{
							pos:        position{line: 163, col: 24, offset: 3858},
							val:        "or",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "FilterPrimary",
			pos:  position{line: 170, col: 1, offset: 4037},
			expr: &actionExpr{
				pos: position{line: 170, col: 18, offset: 4054},
				run: (*parser).callonFilterPrimary1,
				expr: &seqExpr{
					pos: position{line: 170, col: 18, offset: 4054},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 170, col: 18, offset: 4054},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 170, col: 23, offset: 4059},
								name: "Expr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 170, col: 28, offset: 4064},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 170, col: 30, offset: 4066},
							label: "op",
							expr: &ruleRefExpr{
								pos:  position{line: 170, col: 33, offset: 4069},
								name: "FilterPriOp",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 170, col: 45, offset: 4081},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 170, col: 47, offset: 4083},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 170, col: 53, offset: 4089},
								name: "Value",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 170, col: 59, offset: 4095},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "FilterPriOp",
			pos:  position{line: 174, col: 1, offset: 4169},
			expr: &choiceExpr{
				pos: position{line: 174, col: 16, offset: 4184},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 174, col: 16, offset: 4184},
						val:        "==",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 174, col: 23, offset: 4191},
						val:        "!=",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 174, col: 30, offset: 4198},
						val:        "<",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 174, col: 36, offset: 4204},
						val:        ">",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 174, col: 42, offset: 4210},
						val:        "<=",
						ignoreCase: false,
					},
					&actionExpr{
						pos: position{line: 174, col: 49, offset: 4217},
						run: (*parser).callonFilterPriOp7,
						expr: &litMatcher{
							pos:        position{line: 174, col: 49, offset: 4217},
							val:        ">=",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "BranchDo",
			pos:  position{line: 181, col: 1, offset: 4289},
			expr: &actionExpr{
				pos: position{line: 181, col: 13, offset: 4301},
				run: (*parser).callonBranchDo1,
				expr: &seqExpr{
					pos: position{line: 181, col: 13, offset: 4301},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 181, col: 13, offset: 4301},
							val:        "branch(",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 181, col: 23, offset: 4311},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 181, col: 25, offset: 4313},
							label: "br",
							expr: &ruleRefExpr{
								pos:  position{line: 181, col: 28, offset: 4316},
								name: "BranchPrimary",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 181, col: 42, offset: 4330},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 181, col: 44, offset: 4332},
							val:        ")",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "BranchPrimary",
			pos:  position{line: 188, col: 1, offset: 4527},
			expr: &actionExpr{
				pos: position{line: 188, col: 18, offset: 4544},
				run: (*parser).callonBranchPrimary1,
				expr: &seqExpr{
					pos: position{line: 188, col: 18, offset: 4544},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 188, col: 18, offset: 4544},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 188, col: 23, offset: 4549},
								name: "Expr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 188, col: 28, offset: 4554},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 188, col: 30, offset: 4556},
							label: "op",
							expr: &ruleRefExpr{
								pos:  position{line: 188, col: 33, offset: 4559},
								name: "BranchPriOp",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 188, col: 45, offset: 4571},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 188, col: 47, offset: 4573},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 188, col: 54, offset: 4580},
								name: "Value",
							},
						},
					},
				},
			},
		},
		{
			name: "BranchPriOp",
			pos:  position{line: 192, col: 1, offset: 4631},
			expr: &ruleRefExpr{
				pos:  position{line: 192, col: 16, offset: 4646},
				name: "FilterPriOp",
			},
		},
		{
			name: "CountAgg",
			pos:  position{line: 197, col: 1, offset: 4698},
			expr: &actionExpr{
				pos: position{line: 197, col: 13, offset: 4710},
				run: (*parser).callonCountAgg1,
				expr: &seqExpr{
					pos: position{line: 197, col: 13, offset: 4710},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 197, col: 13, offset: 4710},
							val:        "count(",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 197, col: 22, offset: 4719},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 197, col: 24, offset: 4721},
							label: "args",
							expr: &zeroOrOneExpr{
								pos: position{line: 197, col: 29, offset: 4726},
								expr: &ruleRefExpr{
									pos:  position{line: 197, col: 29, offset: 4726},
									name: "FilterMulti",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 197, col: 42, offset: 4739},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 197, col: 44, offset: 4741},
							val:        ")",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 197, col: 48, offset: 4745},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 197, col: 50, offset: 4747},
							label: "alias",
							expr: &zeroOrOneExpr{
								pos: position{line: 197, col: 56, offset: 4753},
								expr: &ruleRefExpr{
									pos:  position{line: 197, col: 56, offset: 4753},
									name: "AliasG",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "MaxAgg",
			pos:  position{line: 207, col: 1, offset: 4931},
			expr: &actionExpr{
				pos: position{line: 207, col: 11, offset: 4941},
				run: (*parser).callonMaxAgg1,
				expr: &seqExpr{
					pos: position{line: 207, col: 11, offset: 4941},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 207, col: 11, offset: 4941},
							val:        "max(",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 207, col: 18, offset: 4948},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 207, col: 20, offset: 4950},
							label: "field",
							expr: &ruleRefExpr{
								pos:  position{line: 207, col: 26, offset: 4956},
								name: "Variable",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 207, col: 35, offset: 4965},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 207, col: 37, offset: 4967},
							label: "args",
							expr: &zeroOrOneExpr{
								pos: position{line: 207, col: 42, offset: 4972},
								expr: &seqExpr{
									pos: position{line: 207, col: 43, offset: 4973},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 207, col: 43, offset: 4973},
											val:        ",",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 207, col: 47, offset: 4977},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 207, col: 49, offset: 4979},
											name: "FilterMulti",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 207, col: 63, offset: 4993},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 207, col: 65, offset: 4995},
							val:        ")",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 207, col: 69, offset: 4999},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 207, col: 71, offset: 5001},
							label: "alias",
							expr: &zeroOrOneExpr{
								pos: position{line: 207, col: 77, offset: 5007},
								expr: &ruleRefExpr{
									pos:  position{line: 207, col: 77, offset: 5007},
									name: "AliasG",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "MinAgg",
			pos:  position{line: 229, col: 1, offset: 5473},
			expr: &actionExpr{
				pos: position{line: 229, col: 11, offset: 5483},
				run: (*parser).callonMinAgg1,
				expr: &seqExpr{
					pos: position{line: 229, col: 11, offset: 5483},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 229, col: 11, offset: 5483},
							val:        "min(",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 229, col: 18, offset: 5490},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 229, col: 20, offset: 5492},
							label: "field",
							expr: &ruleRefExpr{
								pos:  position{line: 229, col: 26, offset: 5498},
								name: "Variable",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 229, col: 35, offset: 5507},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 229, col: 37, offset: 5509},
							label: "args",
							expr: &zeroOrOneExpr{
								pos: position{line: 229, col: 42, offset: 5514},
								expr: &seqExpr{
									pos: position{line: 229, col: 43, offset: 5515},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 229, col: 43, offset: 5515},
											val:        ",",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 229, col: 47, offset: 5519},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 229, col: 49, offset: 5521},
											name: "FilterMulti",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 229, col: 63, offset: 5535},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 229, col: 65, offset: 5537},
							val:        ")",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 229, col: 69, offset: 5541},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 229, col: 71, offset: 5543},
							label: "alias",
							expr: &zeroOrOneExpr{
								pos: position{line: 229, col: 77, offset: 5549},
								expr: &ruleRefExpr{
									pos:  position{line: 229, col: 77, offset: 5549},
									name: "AliasG",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "AvgAgg",
			pos:  position{line: 251, col: 1, offset: 6014},
			expr: &actionExpr{
				pos: position{line: 251, col: 11, offset: 6024},
				run: (*parser).callonAvgAgg1,
				expr: &seqExpr{
					pos: position{line: 251, col: 11, offset: 6024},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 251, col: 11, offset: 6024},
							val:        "avg(",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 251, col: 18, offset: 6031},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 251, col: 20, offset: 6033},
							label: "field",
							expr: &ruleRefExpr{
								pos:  position{line: 251, col: 26, offset: 6039},
								name: "Variable",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 251, col: 35, offset: 6048},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 251, col: 37, offset: 6050},
							label: "args",
							expr: &zeroOrOneExpr{
								pos: position{line: 251, col: 42, offset: 6055},
								expr: &seqExpr{
									pos: position{line: 251, col: 43, offset: 6056},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 251, col: 43, offset: 6056},
											val:        ",",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 251, col: 47, offset: 6060},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 251, col: 49, offset: 6062},
											name: "FilterMulti",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 251, col: 63, offset: 6076},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 251, col: 65, offset: 6078},
							val:        ")",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 251, col: 69, offset: 6082},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 251, col: 71, offset: 6084},
							label: "alias",
							expr: &zeroOrOneExpr{
								pos: position{line: 251, col: 77, offset: 6090},
								expr: &ruleRefExpr{
									pos:  position{line: 251, col: 77, offset: 6090},
									name: "AliasG",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "VarAgg",
			pos:  position{line: 273, col: 1, offset: 6555},
			expr: &actionExpr{
				pos: position{line: 273, col: 11, offset: 6565},
				run: (*parser).callonVarAgg1,
				expr: &seqExpr{
					pos: position{line: 273, col: 11, offset: 6565},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 273, col: 11, offset: 6565},
							val:        "var(",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 273, col: 18, offset: 6572},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 273, col: 20, offset: 6574},
							label: "field",
							expr: &ruleRefExpr{
								pos:  position{line: 273, col: 26, offset: 6580},
								name: "Variable",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 273, col: 35, offset: 6589},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 273, col: 37, offset: 6591},
							label: "args",
							expr: &zeroOrOneExpr{
								pos: position{line: 273, col: 42, offset: 6596},
								expr: &seqExpr{
									pos: position{line: 273, col: 43, offset: 6597},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 273, col: 43, offset: 6597},
											val:        ",",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 273, col: 47, offset: 6601},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 273, col: 49, offset: 6603},
											name: "FilterMulti",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 273, col: 63, offset: 6617},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 273, col: 65, offset: 6619},
							val:        ")",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 273, col: 69, offset: 6623},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 273, col: 71, offset: 6625},
							label: "alias",
							expr: &zeroOrOneExpr{
								pos: position{line: 273, col: 77, offset: 6631},
								expr: &ruleRefExpr{
									pos:  position{line: 273, col: 77, offset: 6631},
									name: "AliasG",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "AliasG",
			pos:  position{line: 297, col: 1, offset: 7153},
			expr: &actionExpr{
				pos: position{line: 297, col: 11, offset: 7163},
				run: (*parser).callonAliasG1,
				expr: &seqExpr{
					pos: position{line: 297, col: 11, offset: 7163},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 297, col: 11, offset: 7163},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 297, col: 13, offset: 7165},
							val:        "as",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 297, col: 18, offset: 7170},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 297, col: 20, offset: 7172},
							label: "alias",
							expr: &ruleRefExpr{
								pos:  position{line: 297, col: 26, offset: 7178},
								name: "Variable",
							},
						},
					},
				},
			},
		},
	},
}

func (c *current) onMain1(agg, rest interface{}) (interface{}, error) {

	jobs := []interface{}{agg}
	rst := cast.ToIfaceSlice(rest)

	for _, v := range rst {
		rstJob := cast.ToIfaceSlice(v)
		if len(rstJob) == 4 {
			jobs = append(jobs, rstJob[3])
		}
	}

	return jobs, nil
}

func (p *parser) callonMain1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMain1(stack["agg"], stack["rest"])
}

func (c *current) onExpr1() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpr1()
}

func (c *current) onValue1(val interface{}) (interface{}, error) {

	return val, nil
}

func (p *parser) callonValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue1(stack["val"])
}

func (c *current) onVariable1() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonVariable1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVariable1()
}

func (c *current) onVariable_Value1(vrbl interface{}) (interface{}, error) {

	return vrbl, nil
}

func (p *parser) callonVariable_Value1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVariable_Value1(stack["vrbl"])
}

func (c *current) onVariable_Literal1(vrbl interface{}) (interface{}, error) {

	vari, _ := cast.TryString(vrbl)
	return cast.GetStringValue(vari), nil
}

func (p *parser) callonVariable_Literal1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVariable_Literal1(stack["vrbl"])
}

func (c *current) onString_Type11() (interface{}, error) {

	c.text = bytes.Replace(c.text, []byte(`\/`), []byte(`/`), -1)
	str, _ := strconv.Unquote(string(c.text))

	return cast.GetStringValue(str), nil
}

func (p *parser) callonString_Type11() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString_Type11()
}

func (c *current) onWord1() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonWord1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWord1()
}

func (c *current) onNumber1() (interface{}, error) {

	return strconv.ParseInt(string(c.text), 10, 64)
}

func (p *parser) callonNumber1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber1()
}

func (c *current) onFileJobG1(filename interface{}) (interface{}, error) {

	if fname, ok := cast.TryString(filename); ok {
		return FileJob{Filename: fname}, nil
	}
	return nil, errors.New("could not decode source file name")
}

func (p *parser) callonFileJobG1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFileJobG1(stack["filename"])
}

func (c *current) onFileName1(name, ext interface{}) (interface{}, error) {

	nm, _ := cast.TryString(name)
	ex, _ := cast.TryString(ext)

	return nm + "." + ex, nil
}

func (p *parser) callonFileName1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFileName1(stack["name"], stack["ext"])
}

func (c *current) onDoJobG1(job interface{}) (interface{}, error) {

	return DoNodeJob{Function: job}, nil
}

func (p *parser) callonDoJobG1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDoJobG1(stack["job"])
}

func (c *current) onAggJobG1(job, rest, params interface{}) (interface{}, error) {

	jobSlices := cast.ToIfaceSlice(rest)
	jobs := []interface{}{job}

	for _, v := range jobSlices {
		j := cast.ToIfaceSlice(v)
		jobs = append(jobs, j[2])
	}

	ps, _ := params.([]string)

	return AggNodeJob{Functions: jobs, GroupBy: ps}, nil
}

func (p *parser) callonAggJobG1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAggJobG1(stack["job"], stack["rest"], stack["params"])
}

func (c *current) onAggGroupBy1(param, rest interface{}) (interface{}, error) {

	p1, _ := cast.TryString(param)
	params := []string{p1}

	restSlice := cast.ToIfaceSlice(rest)
	for _, v := range restSlice {
		ps := cast.ToIfaceSlice(v)
		p2, _ := cast.TryString(ps[2])
		params = append(params, p2)
	}

	return params, nil
}

func (p *parser) callonAggGroupBy1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAggGroupBy1(stack["param"], stack["rest"])
}

func (c *current) onStdOutG1() (interface{}, error) {

	return SinkJob{Type: "stdout"}, nil
}

func (p *parser) callonStdOutG1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStdOutG1()
}

func (c *current) onBlackHoleG1() (interface{}, error) {

	return SinkJob{Type: "blackhole"}, nil
}

func (p *parser) callonBlackHoleG1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBlackHoleG1()
}

func (c *current) onFilterDo1(filt interface{}) (interface{}, error) {

	if f, ok := filt.(Filter); ok {
		return f, nil
	}
	return nil, errors.New("Could not parse filter")
}

func (p *parser) callonFilterDo1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFilterDo1(stack["filt"])
}

func (c *current) onFilterMulti1(first, rest interface{}) (interface{}, error) {

	return newSecondaryFilter(first, rest), nil
}

func (p *parser) callonFilterMulti1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFilterMulti1(stack["first"], stack["rest"])
}

func (c *current) onFilterFactor2(sf interface{}) (interface{}, error) {

	return sf, nil
}

func (p *parser) callonFilterFactor2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFilterFactor2(stack["sf"])
}

func (c *current) onFilterFactor8(pf interface{}) (interface{}, error) {

	return pf, nil
}

func (p *parser) callonFilterFactor8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFilterFactor8(stack["pf"])
}

func (c *current) onFilterSecOp3() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonFilterSecOp3() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFilterSecOp3()
}

func (c *current) onFilterPrimary1(name, op, value interface{}) (interface{}, error) {

	return newPrimaryFilter(name.(string), op, value), nil
}

func (p *parser) callonFilterPrimary1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFilterPrimary1(stack["name"], stack["op"], stack["value"])
}

func (c *current) onFilterPriOp7() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonFilterPriOp7() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFilterPriOp7()
}

func (c *current) onBranchDo1(br interface{}) (interface{}, error) {

	if branch, ok := cast.TryString(br); ok {
		return Branch{Condition: branch}, nil
	}
	return nil, errors.New("Could not decode branch syntax")
}

func (p *parser) callonBranchDo1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBranchDo1(stack["br"])
}

func (c *current) onBranchPrimary1(name, op, value interface{}) (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonBranchPrimary1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBranchPrimary1(stack["name"], stack["op"], stack["value"])
}

func (c *current) onCountAgg1(args, alias interface{}) (interface{}, error) {

	name, filter, err := parseAggArgs(alias, args)
	if err != nil {
		return nil, err
	}

	return Count{Alias: name, Filter: filter}, nil
}

func (p *parser) callonCountAgg1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCountAgg1(stack["args"], stack["alias"])
}

func (c *current) onMaxAgg1(field, args, alias interface{}) (interface{}, error) {

	var name string
	var filter Filter
	var err error

	if args != nil {
		if ags := cast.ToIfaceSlice(args); ags != nil {
			name, filter, err = parseAggArgs(alias, ags[2])
		}
	} else {
		name, filter, err = parseAggArgs(alias, nil)
	}

	if err != nil {
		return nil, err
	}

	fld, _ := cast.TryString(field)
	return Max{Alias: name, Field: fld, Filter: filter}, nil
}

func (p *parser) callonMaxAgg1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMaxAgg1(stack["field"], stack["args"], stack["alias"])
}

func (c *current) onMinAgg1(field, args, alias interface{}) (interface{}, error) {

	var name string
	var filter Filter
	var err error

	if args != nil {
		if ags := cast.ToIfaceSlice(args); ags != nil {
			name, filter, err = parseAggArgs(alias, ags[2])
		}
	} else {
		name, filter, err = parseAggArgs(alias, nil)
	}

	if err != nil {
		return nil, err
	}

	fld, _ := cast.TryString(field)
	return Min{Alias: name, Field: fld, Filter: filter}, nil
}

func (p *parser) callonMinAgg1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMinAgg1(stack["field"], stack["args"], stack["alias"])
}

func (c *current) onAvgAgg1(field, args, alias interface{}) (interface{}, error) {

	var name string
	var filter Filter
	var err error

	if args != nil {
		if ags := cast.ToIfaceSlice(args); ags != nil {
			name, filter, err = parseAggArgs(alias, ags[2])
		}
	} else {
		name, filter, err = parseAggArgs(alias, nil)
	}

	if err != nil {
		return nil, err
	}

	fld, _ := cast.TryString(field)
	return Avg{Alias: name, Field: fld, Filter: filter}, nil
}

func (p *parser) callonAvgAgg1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAvgAgg1(stack["field"], stack["args"], stack["alias"])
}

func (c *current) onVarAgg1(field, args, alias interface{}) (interface{}, error) {

	var name string
	var filter Filter
	var err error

	if args != nil {
		if ags := cast.ToIfaceSlice(args); ags != nil {
			name, filter, err = parseAggArgs(alias, ags[2])
		}
	} else {
		name, filter, err = parseAggArgs(alias, nil)
	}

	if err != nil {
		return nil, err
	}

	fld, _ := cast.TryString(field)
	return Variance{Alias: name, Field: fld, Filter: filter}, nil

}

func (p *parser) callonVarAgg1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVarAgg1(stack["field"], stack["args"], stack["alias"])
}

func (c *current) onAliasG1(alias interface{}) (interface{}, error) {

	if name, ok := cast.TryString(alias); ok {
		return name, nil
	}
	return nil, errors.New("Could not decode alias")
}

func (p *parser) callonAliasG1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAliasG1(stack["alias"])
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

var statePool = &sync.Pool{
	New: func() interface{} { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	ignoreCase := ""
	if lit.ignoreCase {
		ignoreCase = "i"
	}
	val := string(strconv.AppendQuote([]byte{}, lit.val)) + ignoreCase // wrap 'lit.val' with double quotes
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, val)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, val)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
